import { readFile } from 'node:fs/promises'
import { extname, resolve } from 'node:path'

import { generateModels } from './generate-models.js'
import { generateRuntime, generateRuntimeInternal } from './generate-runtime.js'
import { normalizeOpenApi } from './openapi.js'
import { writeGeneratedFile } from './write-file.js'

const generatedAgentGuide = `# Generated API Code Agent Guide

This directory is automatically generated by the \`request-codegen\` CLI.

AI coding agents must not modify files in this directory directly. If the
generated API code needs to be updated, find the relevant \`request-codegen\`
generation command in the root \`package.json\` and run that command instead.
`

export type CliOptions = {
  input: string
  out: string
}

export async function main(argv = process.argv.slice(2)) {
  try {
    await runCli(argv)

    return 0
  } catch (error) {
    console.error(error instanceof Error ? error.message : error)

    return 1
  }
}

export async function runCli(argv: string[], cwd = process.cwd()) {
  const options = parseArgs(argv)
  const inputPath = resolve(cwd, options.input)
  const outDir = resolve(cwd, options.out)
  const document = await readOpenApiJson(inputPath)
  const openapi = normalizeOpenApi(document)

  await writeGeneratedFile(resolve(outDir, 'AGENT.md'), generatedAgentGuide)
  await writeGeneratedFile(resolve(outDir, 'models.ts'), generateModels(openapi))
  await writeGeneratedFile(resolve(outDir, 'request.ts'), generateRuntime(openapi))
  await writeGeneratedFile(
    resolve(outDir, 'request.internal.ts'),
    generateRuntimeInternal(openapi),
  )
}

export function parseArgs(argv: string[]): CliOptions {
  const options: Partial<CliOptions> = {}

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]

    switch (arg) {
      case '--':
        break
      case '--input':
        options.input = readArgValue(argv, index, '--input')
        index += 1
        break
      case '--out':
        options.out = readArgValue(argv, index, '--out')
        index += 1
        break
      default:
        throw new Error(`Unknown argument: ${arg}`)
    }
  }

  if (!options.input) {
    throw new Error('Missing required --input <swagger-json-path> argument.')
  }

  if (!options.out) {
    throw new Error('Missing required --out <output-directory> argument.')
  }

  return {
    input: options.input,
    out: options.out,
  }
}

async function readOpenApiJson(inputPath: string) {
  if (extname(inputPath) !== '.json') {
    throw new Error('Only JSON OpenAPI files are supported.')
  }

  try {
    return JSON.parse(await readFile(inputPath, 'utf8')) as unknown
  } catch (error) {
    if (error instanceof SyntaxError) {
      throw new Error(`Failed to parse JSON OpenAPI file: ${inputPath}`)
    }

    throw error
  }
}

function readArgValue(argv: string[], index: number, name: string) {
  const value = argv[index + 1]

  if (!value || value.startsWith('--')) {
    throw new Error(`Missing value for ${name}.`)
  }

  return value
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const exitCode = await main()
  process.exitCode = exitCode
}
