import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { afterEach, describe, expect, it } from 'vitest'

import { parseArgs, runCli } from './cli.js'

const tempDirs: string[] = []

afterEach(async () => {
  await Promise.all(tempDirs.map((directory) => rm(directory, {
    force: true,
    recursive: true,
  })))
  tempDirs.length = 0
})

describe('cli', () => {
  it('parses required input and output arguments', () => {
    expect(parseArgs(['--', '--input', 'openapi.json', '--out', 'generated'])).toEqual({
      input: 'openapi.json',
      out: 'generated',
    })
  })

  it('writes generated files to the selected output directory', async () => {
    const cwd = await createTempDir()
    const input = join(cwd, 'openapi.json')
    const out = join(cwd, 'generated-api')
    await writeFile(input, JSON.stringify({
      openapi: '3.0.3',
      paths: {
        '/account/count': {
          get: {
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                    },
                  },
                },
              },
            },
          },
        },
      },
    }), 'utf8')

    await runCli(['--input', input, '--out', out], cwd)

    await expect(readFile(join(out, 'models.ts'), 'utf8')).resolves.toContain(
      '"GET/account/count"',
    )
    await expect(readFile(join(out, 'request.ts'), 'utf8')).resolves.toContain(
      'export const requestHttp',
    )
    await expect(readFile(join(out, 'request.ts'), 'utf8')).resolves.toContain(
      "from './request.internal'",
    )
    await expect(readFile(join(out, 'request.internal.ts'), 'utf8')).resolves.toContain(
      'export function parseRequestEndpoint',
    )
    await expect(readFile(join(out, 'AGENT.md'), 'utf8')).resolves.toContain(
      'This directory is automatically generated by the `request-codegen` CLI.',
    )
    await expect(readFile(join(out, 'AGENT.md'), 'utf8')).resolves.toContain(
      'find the relevant `request-codegen`',
    )
    await expect(readFile(join(out, 'AGENT.md'), 'utf8')).resolves.toContain(
      'root `package.json`',
    )
  })

  it('refuses to overwrite non-generated output files', async () => {
    const cwd = await createTempDir()
    const input = join(cwd, 'openapi.json')
    const out = join(cwd, 'generated-api')
    await writeFile(input, JSON.stringify({
      openapi: '3.0.3',
      paths: {},
    }), 'utf8')
    await writeFile(join(out, 'models.ts'), 'hand written', 'utf8').catch(async () => {
      await runCli(['--input', input, '--out', out], cwd)
      await writeFile(join(out, 'models.ts'), 'hand written', 'utf8')
    })

    await expect(runCli(['--input', input, '--out', out], cwd)).rejects.toThrow(
      'Refusing to overwrite non-generated file',
    )
  })

  it('rejects non-json input paths', async () => {
    const cwd = await createTempDir()
    const input = join(cwd, 'openapi.yaml')
    await writeFile(input, 'openapi: 3.0.3', 'utf8')

    await expect(runCli(['--input', input, '--out', 'generated'], cwd)).rejects.toThrow(
      'Only JSON OpenAPI files are supported.',
    )
  })
})

async function createTempDir() {
  const directory = await mkdtemp(join(tmpdir(), 'request-codegen-'))
  tempDirs.push(directory)

  return directory
}
