import type {
  NormalizedEndpoint,
  NormalizedOpenApi,
  NormalizedParameter,
  UnknownRecord,
} from './openapi.js'
import {
  renderComponentSchemas,
  renderObjectType,
  renderPropertyName,
  renderSchemaType,
  type TsProperty,
} from './schema-to-ts.js'

export function generateModels(openapi: NormalizedOpenApi) {
  const sections = [
    renderGeneratedHeader(),
    renderComponentSchemas(openapi.componentSchemas),
    renderIModels(openapi.endpoints),
  ].filter(Boolean)

  return `${sections.join('\n\n')}\n`
}

function renderGeneratedHeader() {
  return `/* This file is automatically generated by request-codegen. Do not modify. */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck`
}

function renderIModels(endpoints: NormalizedEndpoint[]) {
  const entries = endpoints.map(renderEndpointModel).join('\n')

  return `export interface IModels {\n${entries}}`
}

function renderEndpointModel(endpoint: NormalizedEndpoint) {
  const comments = [
    endpoint.summary && `Interface name: ${endpoint.summary}`,
    endpoint.description && `Description: ${endpoint.description}`,
  ].filter((comment): comment is string => Boolean(comment))
  const commentBlock = renderCommentBlock(comments, '  ')
  const model = [
    `${commentBlock}  ${JSON.stringify(endpoint.id)}: {`,
    `    Header: ${renderParameterObject(endpoint.headerParameters)}`,
    `    Path: ${renderParameterObject(getPathParameters(endpoint))}`,
    `    Query: ${renderParameterObject(endpoint.queryParameters)}`,
    `    Body: ${renderSchemaType(endpoint.bodySchema ?? emptyObjectSchema())}`,
    `    Res: ${renderSchemaType(endpoint.responseSchema ?? emptyObjectSchema())}`,
    '  }',
  ]

  return `${model.join('\n')}\n`
}

function getPathParameters(endpoint: NormalizedEndpoint) {
  const parameters = new Map<string, NormalizedParameter>()
  const pathParametersByName = new Map(
    endpoint.pathParameters.map((parameter) => [parameter.name, parameter]),
  )

  for (const name of endpoint.pathParameterNames) {
    const declaredParameter = pathParametersByName.get(name)

    parameters.set(
      name,
      declaredParameter
        ? { ...declaredParameter, required: true }
        : {
            in: 'path',
            name,
            required: true,
            schema: { type: 'string' },
          },
    )
  }

  return [...parameters.values()].sort((left, right) => left.name.localeCompare(right.name))
}

function renderParameterObject(parameters: NormalizedParameter[]) {
  return renderObjectType(parameters.map(parameterToProperty))
}

function parameterToProperty(parameter: NormalizedParameter): TsProperty {
  return {
    description: parameter.description,
    name: parameter.name,
    required: parameter.required,
    type: renderSchemaType(parameter.schema),
  }
}

function renderCommentBlock(lines: string[], indent: string) {
  if (lines.length === 0) {
    return ''
  }

  return `${indent}/**\n${lines.map((line) => `${indent} * ${escapeComment(line)}`).join('\n')}\n${indent} */\n`
}

function emptyObjectSchema(): UnknownRecord {
  return { type: 'object' }
}

function escapeComment(value: string) {
  return value.replace(/\*\//g, '*\\/')
}

export function renderEndpointKey(endpoint: string) {
  return renderPropertyName(endpoint)
}
