import { describe, expect, it } from 'vitest'

import { generateModels } from './generate-models.js'
import type { NormalizedOpenApi } from './openapi.js'

describe('generateModels', () => {
  it('generates models without Req and with path params in Path', () => {
    const openapi: NormalizedOpenApi = {
      componentSchemas: {
        RepositoryInfoResponseDto: {
          properties: {
            data: { $ref: '#/components/schemas/RepositoryInfoDataDto' },
          },
          required: ['data'],
          type: 'object',
        },
        RepositoryInfoDataDto: {
          properties: {
            name: { type: 'string' },
          },
          type: 'object',
        },
      },
      endpoints: [
        {
          headerParameters: [
            {
              in: 'header',
              name: 'x-request-id',
              required: false,
              schema: { type: 'string' },
            },
          ],
          id: 'GET/repository/{id}',
          method: 'GET',
          path: '/repository/{id}',
          pathParameterNames: ['id'],
          pathParameters: [
            {
              description: 'Repository id',
              in: 'path',
              name: 'id',
              required: true,
              schema: { type: 'number' },
            },
            {
              in: 'path',
              name: 'unused',
              required: true,
              schema: { type: 'string' },
            },
          ],
          queryParameters: [
            {
              in: 'query',
              name: 'versionId',
              required: false,
              schema: { type: 'number' },
            },
          ],
          responseSchema: { $ref: '#/components/schemas/RepositoryInfoResponseDto' },
          summary: 'Get repository',
        },
      ],
    }

    expect(generateModels(openapi)).toBe(`/* This file is automatically generated by request-codegen. Do not modify. */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type RepositoryInfoDataDto = {
  name?: string
}

export type RepositoryInfoResponseDto = {
  data: RepositoryInfoDataDto
}

export interface IModels {
  /**
   * Interface name: Get repository
   */
  "GET/repository/{id}": {
    Header: {
  "x-request-id"?: string
}
    Path: {
  /**
   * Repository id
   */
  id: number
}
    Query: {
  versionId?: number
}
    Body: {}
    Res: RepositoryInfoResponseDto
  }
}
`)
    expect(generateModels(openapi)).not.toContain('Req:')
    expect(generateModels(openapi)).not.toContain('unused')
  })
})
